{
 "title": "Arma 3 Server",
 "time": { "from": "2023-04-18T23:53:01.534Z", "to": "2023-04-19T00:10:01.159Z" },
 "templating": {
  "list": [
   {
    "name": "Server",
    "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagValues(bucket: \"server_performance\", tag: \"connectedServer\")"
   },
   {
    "name": "Side",
    "label": "Side",
    "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagValues(bucket: \"server_performance\", tag: \"side\")"
   },
   { "name": "Datasource", "query": "influxdb" }
  ]
 },
 "panels": [
  { "title": "Core Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Mission Time Elapsed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mission_data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"server_time\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"serverTime\")\r\n  |> filter(fn: (r) => r[\"connectedServer\"] == \"${Server}\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Server & HC FPS",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 7, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"server_performance\")\r\n|> range(start: -1m)\r\n|> filter(fn: (r) => r[\"_measurement\"] == \"fps\")\r\n|> filter(fn: (r) => r[\"_field\"] == \"fps_avg\")\r\n|> filter(fn: (r) => r[\"connectedServer\"] == \"${Server}\")\r\n|> group(columns: [\"profileName\", \"_field\"])\r\n|> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n|> keep(columns: [\"_time\", \"profileName\", \"_field\", \"_value\"])\r\n|> map(fn: (r) => ({ r with _field: \"Avg FPS\" }))\r\n|> last()"
    },
    {
     "query": "from(bucket: \"server_performance\")\r\n|> range(start: -1m)\r\n|> filter(fn: (r) => r[\"_measurement\"] == \"fps\")\r\n|> filter(fn: (r) => r[\"_field\"] == \"fps_min\")\r\n|> filter(fn: (r) => r[\"connectedServer\"] == \"${Server}\")\r\n|> group(columns: [\"profileName\", \"_field\"])\r\n|> aggregateWindow(every: v.windowPeriod, fn: min, createEmpty: false)\r\n|> keep(columns: [\"_time\", \"profileName\", \"_field\", \"_value\"])\r\n|> map(fn: (r) => ({ r with _field: \"Min FPS\" }))\r\n|> last()"
    }
   ]
  },
  {
   "title": "Running Scripts",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"server_performance\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"running_scripts\")\r\n  |> filter(fn: (r) => r[\"connectedServer\"] == \"${Server}\")\r\n  |> keep(columns: [\"_time\", \"profileName\", \"_field\", \"_value\"])\r\n  |> group(columns: [\"profileName\", \"_field\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: true)"
    }
   ]
  },
  {
   "title": "Alive Players",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"server_performance\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"entities_global\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"players_alive\")\r\n  |> filter(fn: (r) => r[\"profileName\"] == \"${Server}\")\r\n  |> filter(fn: (r) => r[\"profileName\"] == \"${Server}\")\r\n  |> group(columns: [\"side\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Milsim CPS Raw",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"server_performance\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"connectedServer\"] == \"${Server}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"milsim_server_efficiency\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"milsim_raw_cps\")\r\n  |> last()\r\n  |> map(fn: (r) => ({ r with _field: \"CPS RAW\" }))"
    }
   ]
  },
  {
   "title": "Milsim CPS",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"server_performance\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"connectedServer\"] == \"${Server}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"milsim_server_efficiency\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"milsim_cps\")\r\n  |> last()\r\n  |> map(fn: (r) => ({ r with _field: \"CPS\" }))"
    }
   ]
  },
  {
   "title": "Running Mission",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 13, "x": 11, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"mission_data\")\r\n  |> range(start: -7d)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"running_mission\")\r\n  |> filter(fn: (r) => r[\"connectedServer\"] == \"${Server}\")\r\n  |> last()\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> keep(columns: [\"briefing_name\", \"mission_name\", \"mission_name_source\", \"on_load_name\", \"author\", \"server_name\", \"_time\", \"_value\"])\r\n"
    }
   ]
  },
  {
   "title": "Server FPS History",
   "type": "heatmap",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 11 },
   "targets": [
    {
     "query": "from(bucket: \"server_performance\")\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r[\"_measurement\"] == \"fps\")\r\n|> filter(fn: (r) => r[\"_field\"] == \"fps_avg\")\r\n|> filter(fn: (r) => r[\"connectedServer\"] == \"${Server}\")\r\n|> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n|> yield(name: \"avg\")"
    },
    {
     "query": "from(bucket: \"server_performance\")\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r[\"_measurement\"] == \"fps\")\r\n|> filter(fn: (r) => r[\"_field\"] == \"fps_min\")\r\n|> filter(fn: (r) => r[\"connectedServer\"] == \"${Server}\")\r\n|> aggregateWindow(every: v.windowPeriod, fn: min, createEmpty: false)\r\n|> yield(name: \"min\")"
    }
   ]
  },
  {
   "title": "Global Objects, Groups, Units",
   "type": "stat",
   "gridPos": { "h": 5, "w": 13, "x": 11, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "  from(bucket: \"server_performance\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"entities_global\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"units_alive\")\r\n  |> filter(fn: (r) => r[\"profileName\"] == \"${Server}\")\r\n  |> group(columns: [\"side\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: true)\r\n  |> keep(columns: [\"_time\", \"_measurement\", \"_value\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: true)\r\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "query": "from(bucket: \"server_performance\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"entities_global\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"units_dead\")\r\n  |> filter(fn: (r) => r[\"profileName\"] == \"${Server}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: true)\r\n  |> keep(columns: [\"_time\", \"_measurement\", \"_value\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: true)\r\n"
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"server_performance\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"entities_global\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"vehicles_total\")\r\n  |> filter(fn: (r) => r[\"connectedServer\"] == \"${Server}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: true)\r\n  |> keep(columns: [\"_time\", \"_measurement\", \"_value\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: true)\r\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"server_performance\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"entities_global\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"vehicles_weaponholder\")\r\n  |> filter(fn: (r) => r[\"connectedServer\"] == \"${Server}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: true)\r\n  |> keep(columns: [\"_time\", \"_measurement\", \"_value\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: true)\r\n\r\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"server_performance\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"entities_global\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"groups_total\")\r\n  |> filter(fn: (r) => r[\"connectedServer\"] ==  \"${Server}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: true)\r\n  |> keep(columns: [\"_time\", \"_measurement\", \"_value\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: true)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "[Global] Active Units",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "  from(bucket: \"server_performance\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"entities_global\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"units_alive\")\r\n  |> filter(fn: (r) => r[\"profileName\"] == \"${Server}\")\r\n  |> group(columns: [\"side\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\r\n  "
    }
   ]
  },
  {
   "title": "Units by Profile",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 9, "y": 18 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"server_performance\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"entities_local\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"units_alive\")\r\n  |> filter(fn: (r) => r[\"connectedServer\"] == \"${Server}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: true)\r\n  |> keep(columns: [\"_time\", \"profileName\", \"_field\", \"_value\"])\r\n  |> map(fn: (r) => ({ r with _field: \"Alive\" }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: true)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "query": "from(bucket: \"server_performance\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"entities_local\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"units_dead\")\r\n  |> filter(fn: (r) => r[\"connectedServer\"] == \"${Server}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: true)\r\n  |> keep(columns: [\"_time\", \"profileName\", \"_field\", \"_value\"])\r\n  |> map(fn: (r) => ({ r with _field: \"Dead\" }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: true)"
    }
   ]
  },
  {
   "title": "Player Ping",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 18 },
   "targets": [
    {
     "query": "from(bucket: \"player_performance\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"network\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"avgPing\")\r\n  |> filter(fn: (r) => r[\"connectedServer\"] == \"${Server}\")\r\n  |> group(columns: [\"playerUID\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "[Global] Active Players",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 21 },
   "targets": [
    {
     "query": "  from(bucket: \"server_performance\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"entities_global\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"players_alive\")\r\n  |> filter(fn: (r) => r[\"profileName\"] == \"${Server}\")\r\n  |> group(columns: [\"side\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\r\n  "
    }
   ]
  },
  {
   "title": "Player Desync",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 23 },
   "targets": [
    {
     "query": "from(bucket: \"player_performance\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"network\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"desync\")\r\n  |> filter(fn: (r) => r[\"connectedServer\"] == \"${Server}\")\r\n  |> group(columns: [\"playerUID\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Groups by Profile",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 9, "y": 24 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"server_performance\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"entities_local\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"groups_total\")\r\n  |> filter(fn: (r) => r[\"connectedServer\"] == \"${Server}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: true)\r\n  |> keep(columns: [\"_time\", \"profileName\", \"_value\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: true)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Player Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 28 },
   "targets": [
    {
     "query": "from(bucket: \"player_performance\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"network\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"avgBandwidth\")\r\n  |> filter(fn: (r) => r[\"connectedServer\"] == \"${Server}\")\r\n  |> group(columns: [\"playerUID\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Vehicles by Profile",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 9, "y": 30 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"server_performance\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"entities_local\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"vehicles_total\" or r[\"_field\"] == \"vehicles_weaponholder\")\r\n  |> filter(fn: (r) => r[\"connectedServer\"] == \"${Server}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: true)\r\n  |> keep(columns: [\"_time\", \"profileName\", \"_value\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: true)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Chat Log",
   "type": "table",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 36 },
   "targets": [
    {
     "query": "from(bucket: \"server_events\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"HandleChatMessage\")\r\n  |> filter(fn: (r) => r[\"connectedServer\"] == \"${Server}\")\r\n  |> filter(fn: (r) => r._field == \"text\" or r._field == \"from\" or r._field == \"channel\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> keep(columns: [\"_time\", \"channel\", \"from\", \"name\", \"text\"])\r\n\r\n  "
    }
   ]
  },
  { "title": "Global Entity Counts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Global Alive Units By Side",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 45 },
   "targets": [
    {
     "query": "from(bucket: \"server_performance\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"entities_global\")\n  |> filter(fn: (r) => r[\"_field\"] == \"units_alive\")\n  |> filter(fn: (r) => r[\"profileName\"] == \"${Server}\")\n  |> map(fn: (r) => ({ r with _field: \"Alive\" }))\n  |> keep(columns: [\"_time\", \"side\", \"_field\", \"_value\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Global Vehicles By Side",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 51 },
   "targets": [
    {
     "query": "from(bucket: \"server_performance\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"entities_global\")\n  |> filter(fn: (r) => r[\"_field\"] == \"vehicles_total\")\n  |> filter(fn: (r) => r[\"profileName\"] == \"${Server}\")\n  |> map(fn: (r) => ({ r with _field: \"Vehicles\" }))\n  |> keep(columns: [\"_time\", \"side\", \"_field\", \"_value\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "collapsed": true
  },
  {
   "title": "Primary Weapons Equipped",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 58 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"player_state\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"unit_loadout\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"primaryWeaponClass\")\r\n  |> duplicate(column: \"_value\", as: \"primaryWeaponClass\")\r\n  |> group(columns: [\"playerUID\", \"primaryWeaponClass\"])\r\n  |> last()\r\n  |> duplicate(column: \"playerUID\", as: \"countPlayers\")\r\n  |> group(columns: [\"primaryWeaponClass\"])\r\n  |> count(column: \"countPlayers\")\r\n  |> group()\r\n  // new field\r\n  |> map (fn: (r) => ({ r with \"columnName\": \"Unit Count\" }))\r\n  |> pivot(rowKey:[\"primaryWeaponClass\"], columnKey: [\"columnName\"], valueColumn: \"countPlayers\")\r\n  |> sort(columns: [\"_value\"], desc: true)\r\n\r\n\r\n"
    }
   ]
  },
  {
   "title": "Current Weapons Equipped",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 58 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"player_state\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"unit_loadout\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"currentWeaponClass\")\r\n  |> duplicate(column: \"_value\", as: \"currentWeaponClass\")\r\n  |> group(columns: [\"playerUID\", \"currentWeaponClass\"])\r\n  |> last()\r\n  |> duplicate(column: \"playerUID\", as: \"countPlayers\")\r\n  |> group(columns: [\"currentWeaponClass\"])\r\n  |> count(column: \"countPlayers\")\r\n  |> group()\r\n  // new field\r\n  |> map (fn: (r) => ({ r with \"columnName\": \"Unit Count\" }))\r\n  |> pivot(rowKey:[\"currentWeaponClass\"], columnKey: [\"columnName\"], valueColumn: \"countPlayers\")\r\n  |> sort(columns: [\"_value\"], desc: true)\r\n\r\n\r\n"
    }
   ]
  },
  {
   "title": "Handgun Weapons Equipped",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 6, "x": 12, "y": 58 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"player_state\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"unit_loadout\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"handgunWeaponClass\")\r\n  |> duplicate(column: \"_value\", as: \"handgunWeaponClass\")\r\n  |> group(columns: [\"playerUID\", \"handgunWeaponClass\"])\r\n  |> last()\r\n  |> duplicate(column: \"playerUID\", as: \"countPlayers\")\r\n  |> group(columns: [\"handgunWeaponClass\"])\r\n  |> count(column: \"countPlayers\")\r\n  |> group()\r\n  // new field\r\n  |> map (fn: (r) => ({ r with \"columnName\": \"Unit Count\" }))\r\n  |> pivot(rowKey:[\"handgunWeaponClass\"], columnKey: [\"columnName\"], valueColumn: \"countPlayers\")\r\n  |> sort(columns: [\"_value\"], desc: true)\r\n\r\n\r\n"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 70 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"recording-data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"unitState\")\r\n  |> filter(fn: (r) => r[\"side\"] == \"EAST\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"isAlive\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Current Weapons Equipped",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 6, "x": 15, "y": 70 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"player_state\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"unit_loadout\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"gogglesClass\")\r\n  |> duplicate(column: \"_value\", as: \"gogglesClass\")\r\n  |> group(columns: [\"playerUID\", \"gogglesClass\"])\r\n  |> last()\r\n  |> duplicate(column: \"playerUID\", as: \"countPlayers\")\r\n  |> group(columns: [\"gogglesClass\"])\r\n  |> count(column: \"countPlayers\")\r\n  |> group()\r\n  // new field\r\n  |> map (fn: (r) => ({ r with \"columnName\": \"Unit Count\" }))\r\n  |> pivot(rowKey:[\"gogglesClass\"], columnKey: [\"columnName\"], valueColumn: \"countPlayers\")\r\n  |> sort(columns: [\"_value\"], desc: true)\r\n\r\n\r\n"
    }
   ]
  }
 ]
}